Geocode Trees Stretch Implementation
Blake2912/Vahini-2.0 pull request #32
Opened 2023-04-03 06:30 UTC by amartyanambiar

This PR solves the problem of geocoding trees by using the Stretch-wise Implementation.
In the upcoming comments, you shall find detailed explanation for changes in the files.

This PR is to be merged into `geocode-trees`
After merge, within `geocode-trees`, work upon the generalisation of the test cases according to the UI selection shall be performed and incorporating validation steps too.

2023-04-03 06:32 UTC, amartyanambiar commented on app.py
> +
Test Case Functions for each stretch 
`basic_science to ganesha_statue` , `ganesha_statue to hostel_turn`

Utilised test_coordinates for test nodes.

2023-04-03 06:33 UTC, amartyanambiar commented on cmritPath.py
> +        #                   ('hostel_turn', 'volley_ball_court')], length=300)
Commented this.
As we no longer are working by this approach.

Path shall be made btwn two nodes in a stretch only when trees are added.

2023-04-03 06:34 UTC, amartyanambiar commented on geocodeTree.py
> +        self.tree_list.append(tree_name)
a list is maintained to store the tree_node names

2023-04-03 06:37 UTC, amartyanambiar commented on geocodeTree.py
> +        self.G.add_edge(self.end_node, self.tree_list[-1])
In this code snippet,

A for loop is run, to connect all consecutive tree nodes with each other bidirectionally.

Before : T1, T2, T3    (not connected)
After : T1 <=> T2 <=> T3  (connected bidirectionally)

Then the  first tree_node is connected to the start_node and the last tree_node is connected to the last_node of the stretch.

first_node <=> T1 <=> T2 <=> T3 <=> last_node

2023-04-03 06:39 UTC, amartyanambiar commented on test_coordinates.py
> +basic_science = Coordinates("basic_science", [12.96626, 77.71211])
added coordinates of nodes (basic_science, ganesha_statue, ganesha_statue, ganesha_statue)

2023-04-04 16:33 UTC, Blake2912 requested changes
```
['cmrit_entrance', 'teacher_parking', 'volley_ball_court', 'basic_science', 'ganesha_statue', 'hostel_turn', 't-1', 't-2', 't-3', 't-4', 't-5', 't-6']
    raise nx.NetworkXNoPath(f"No path between {source} and {target}.")
networkx.exception.NetworkXNoPath: No path between t-1 and volley_ball_court.
```
I m getting this error when I run the `unpickle.py` file @amartyanambiar can you look into what's the issue?

I m not sure if I am missing something I followed the above mentioned instructions

2023-04-04 16:41 UTC, Blake2912 commented
I haven't changed any node here I just ran it from the terminal that's it... so implicitly wouldn't an ideal case get fired up?

2023-04-04 16:44 UTC, amartyanambiar commented
> I haven't changed any node here I just ran it from the terminal that's it... so implicitly wouldn't an ideal case get fired up?

Because I didn't push my unpickle.py.(futile push, nodes keep changing for test cases)
Change nodes in requested shortest_path statement.

2023-04-04 16:53 UTC, merged